FROM node:18-alpine

USER node
WORKDIR '/home/node/app'

EXPOSE 3000

COPY --chown=node:node ./package.json .
RUN npm install
COPY --chown=node:node . .
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]