FROM node:18-alpine

USER node
RUN mkdir -p /home/node/app
RUN mkdir -p /home/node/app/node_modules
WORKDIR '/home/node/app'

EXPOSE 3000
ENV NODE_ENV=DEVELOPMENT

COPY --chown=node:node ./package*.json .
RUN npm ci && npm cache clean --force
COPY --chown=node:node . .
CMD ["npm", "run", "dev", "--","--force", "--host", "0.0.0.0"]
