FROM node:18-alpine

USER node
RUN mkdir -p /home/node/app
RUN mkdir -p /home/node/app/node_modules
WORKDIR '/home/node/app'

EXPOSE 3000

COPY --chown=node:node ./package.json ./package-lock.json ./
RUN npm ci && npm cache clean --force
COPY --chown=node:node . .
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
