version: "3"
services:
  client:
    #if image name and build are provided, the name will be the tag of the image
    #created when running docker compose up --build
    image: lfiggins/codespace-client-dev
    mem_limit: 128m
    hostname: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    # ports:
    #   - "3000:3000"
  redis:
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--requirepass devpassword --save 120 1 --loglevel warning
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /local-redis-data:/data
  api:
    image: lfiggins/codespace-backend-dev
    hostname: api
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /usr/src/app/codespace_backend/__pycache__/
      - ./api/codespace_backend:/usr/src/app/codespace_backend
      - ./api/tests/:/usr/src/app/tests
      - /user/src/app/tests/__pycache__/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PW=devpassword
      - PYTHONUNBUFFERED=1
      - SECRET=721556b2a967182d21c113d80d3f5d3bf415f47ee1e309fab97a0d778d2d131e
    depends_on: 
     - redis
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: lfiggins/codespace-nginx-dev
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
     - "8080:80"
