FROM python:3.10

RUN pip install pipenv
WORKDIR /usr/src/app

COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

COPY . .
RUN pipenv install --editable ./codespace_backend
CMD ["python3", "-m", "flask", "--app", "codespace_backend", "--debug", "run", "--host=0.0.0.0"]