name: Test Api Service
on:
  pull_request:
    branches:
      - main
    paths:
      - api/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Test image
        run: docker build -t lfiggins/codespace-backend-test -f ./api/Dockerfile.dev ./api 
      - name: Run Tests
        run: docker run -e CI=true lfiggins/codespace-backend-test python -m pytest

    